.\"	$OpenBSD$
.\"
.\"
.\" Copyright (c) 2021 Vadim Zhukov <zhuk@openbsd.org>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd $Mdocdate: May 5 2021 $
.Dt TLC 1
.Os
.Sh NAME
.Nm tlc
.Nd count input line interactively
.Sh SYNOPSIS
.Nm
.Op Fl fp
.Op Fl d Ar delim
.Op Fl e Ar end
.Op Fl i Ar interval
.Op Fl s Ar start
.Op Ar text
.Sh DESCRIPTION
The
.Nm
utility reads lines from standard input and, by default,
regularly updates summary line with increasing count of lines read
on standard error descriptor.
.Pp
If
.Ar text
is specified, it is appended to summary line.
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Fl d Ar delim
Changes delimiter used to split input lines to
.Ar delim .
Can be any string; the empty
.Ar delim
is interpreted as
.Ql \\\\0 .
Default is newline character.
.It Fl e Ar end
Display progress in terms of percents instead of line numbers.
The 100% mark will be achivied upon reading
.Ql end-start
lines.
Also enables the
.Sq %p
format code, see below.
It is now allowed to set
.Ar end
less than or equal to
.Ar start .
.It Fl f
Makes
.Ar text
interpreted as format string to be used for displaing summary.
The following format codes are supported:
.Bl -tag -width ws
.It %%
Encodes single percent sign.
.It %i
Replaced with number of lines read.
.It %p
Replaced with progress value, like:
.Ql 42
(the percent sign is not included automatically).
In case of absent
.Ar end ,
this format code does nothing.
.It %s
Replaced with last line read; empty if no lines were read yet.
.El
Every other combination of percent sign and some character will
result in outputting them literally.
.It Fl i Ar interval
Sets minimal number of seconds between summary line updates to
.Ar interval .
This helps to avoid flickering due too often screen updates.
If set to zero, screen will be updated upon each input line read.
Default value is 1 second.
.It Fl p
Enables passthrough mode: every input line gets duplicated on
standard output.
.It Fl s Ar start
Sets initial value of lines read to
.Ar start .
Defaults to 0.
It is now allowed to set
.Ar start
larger than or equal to
.Ar end ,
unless the latter was not specified at all.
.El
.Sh EXIT STATUS
.Ex -std tlc
.Sh EXAMPLES
Show file removal progress:
.Bd -literal -offset indent
$ rm -Rv foo | tlc 'files removed'
42 files removed...
.Ed
.Pp
and eventually the line above will evolve into:
.Bd -literal -offset indent
1764 files removed.
$
.Ed
.Pp
Monitor files as being pushed on pipe:
.Bd -literal -offset indent
$ find /usr/lib -type f -name '*.so' |
  tlc -pf '%i file found: %s' |
  xargs -J % objdump -p % >plugins.log
37 file found: /usr/lib/kid3/libkid3-core.so
<...>
1337 file found: /usr/lib/libkdeinit5_kile.so
$
.Ed
.Sh SEE ALSO
.Xr getline 3
.Sh AUTHORS
.Nm
was written by
.An Vadim Zhukov Aq Mt zhuk@openbsd.org .
