#!/bin/sh

set -e
set -u

name=$1
check_stdout=$2
args=$3

check_stdout=$(echo "$check_stdout" | tr A-Z a-z)
if [ x"$check_stdout" = xyes ]; then
	cat <<EOF

add_custom_command(OUTPUT $name.expectedout
                   COMMAND sh \${CMAKE_CURRENT_SOURCE_DIR}/$name.cmds ">$name.expectedout"
                   DEPENDS $name.cmds
                   COMMENT "sh $name.cmds >$name.expectedout"
                  )
EOF
fi

cat <<EOF

add_test(NAME test-$name
         COMMAND sh \${CMAKE_CURRENT_SOURCE_DIR}/run-test $name $check_stdout \$<TARGET_FILE:tlc> $args
        )

add_custom_target(test-$name
                  sh \${CMAKE_CURRENT_SOURCE_DIR}/run-test $name $check_stdout \$<TARGET_FILE:tlc> $args
                  COMMENT "Running test $name"
EOF

if [ x"$check_stdout" = xyes ]; then
cat <<EOF
                  DEPENDS $name.expectedout
EOF
fi

cat <<EOF
                  VERBATIM
                 )
EOF
